blank_issues_enabled: false
issue_template:
  - chore-request.yml
  - documentation-issue.yml
  - feature-request.yml
  - fix-request.yml
  - installation-issue.yml
  - lib-error.yml
  - perf-request.yml
  - refactor-request.yml
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
